In [15]:
#Importing pandas library
import pandas as pd

#Creating the dataframe of the Crop Recommendation Data Set
df = pd.read_csv('Crop_recommendation.csv')

#Showing the upper 5 data in the dataframe
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   str
dtypes: float64(4), int64(3), str(1)
memory usage: 153.0 KB

In [17]:
#Checking the number of rows and columns in the dataset
df.shape

(2200, 8)

In [18]:
df.isna().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [19]:
#Checking for duplicates in the dataset
df[df.duplicated()]

Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []

In [20]:
print("\nBasic stats:\n", df.describe())

Basic stats:
                  N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000
mean     50.551818    53.362727    48.149091    25.616244    71.481779
std      36.917334    32.985883    50.647931     5.063749    22.263812
min       0.000000     5.000000     5.000000     8.825675    14.258040
25%      21.000000    28.000000    20.000000    22.769375    60.261953
50%      37.000000    51.000000    32.000000    25.598693    80.473146
75%      84.250000    68.000000    49.000000    28.561654    89.948771
max     140.000000   145.000000   205.000000    43.675493    99.981876

                ph     rainfall
count  2200.000000  2200.000000
mean      6.469480   103.463655
std       0.773938    54.958389
min       3.504752    20.211267
25%       5.971693    64.551686
50%       6.425045    94.867624
75%       6.923643   124.267508
max       9.935091   298.560117

In [24]:
#Handle outliers

# Selecting numerical columns
numeric_cols = ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']

def cap_outliers(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    return series.clip(lower_bound, upper_bound)


for col in numeric_cols:

    # Calculate IQR boundaries
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    # Count outliers before capping
    outliers_before = ((df[col] < lower) | (df[col] > upper)).sum()

    # Cap outliers
    df[col] = cap_outliers(df[col])

    # Check outliers after capping
    q1_new = df[col].quantile(0.25)
    q3_new = df[col].quantile(0.75)
    iqr_new = q3_new - q1_new

    lower_new = q1_new - 1.5 * iqr_new
    upper_new = q3_new + 1.5 * iqr_new

    outliers_after = (
        (df[col] < lower_new) | (df[col] > upper_new)
    ).sum()

    print(
        f"{col}: {outliers_before} outliers capped → "
        f"{outliers_after} remaining"
    )

N: 0 outliers capped → 0 remaining
P: 138 outliers capped → 0 remaining
K: 200 outliers capped → 0 remaining
temperature: 86 outliers capped → 0 remaining
humidity: 30 outliers capped → 0 remaining
ph: 57 outliers capped → 0 remaining
rainfall: 100 outliers capped → 0 remaining

In [25]:
#Checking for duplicates in the dataset
df[df.duplicated()]

Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []

In [26]:
df.isna().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [27]:
df[col] = cap_outliers(df[col])

In [28]:
df

        N   P     K  temperature   humidity        ph    rainfall   label
0      90  42  43.0    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41.0    21.770462  80.319644  7.038096  213.841241    rice
2      60  55  44.0    23.004459  82.320763  7.840207  213.841241    rice
3      74  35  40.0    26.491096  80.158363  6.980401  213.841241    rice
4      78  42  42.0    20.130175  81.604873  7.628473  213.841241    rice
...   ...  ..   ...          ...        ...       ...         ...     ...
2195  107  34  32.0    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27.0    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30.0    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34.0    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30.0    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [29]:
df.to_csv('Crop_recommendation_cleaned.csv', index=False)

In [30]:
df

        N   P     K  temperature   humidity        ph    rainfall   label
0      90  42  43.0    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41.0    21.770462  80.319644  7.038096  213.841241    rice
2      60  55  44.0    23.004459  82.320763  7.840207  213.841241    rice
3      74  35  40.0    26.491096  80.158363  6.980401  213.841241    rice
4      78  42  42.0    20.130175  81.604873  7.628473  213.841241    rice
...   ...  ..   ...          ...        ...       ...         ...     ...
2195  107  34  32.0    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27.0    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30.0    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34.0    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30.0    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [31]:
print("\nBasic stats:\n", df.describe())

Basic stats:
                  N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000
mean     50.551818    52.743182    38.376364    25.588740    71.493347
std      36.917334    31.427156    23.460322     4.738804    22.234536
min       0.000000     5.000000     5.000000    14.080956    15.731726
25%      21.000000    28.000000    20.000000    22.769375    60.261953
50%      37.000000    51.000000    32.000000    25.598693    80.473146
75%      84.250000    68.000000    49.000000    28.561654    89.948771
max     140.000000   128.000000    92.500000    37.250073    99.981876

                ph     rainfall
count  2200.000000  2200.000000
mean      6.464205   101.986465
std       0.730288    51.165743
min       4.543768    20.211267
25%       5.971693    64.551686
50%       6.425045    94.867624
75%       6.923643   124.267508
max       8.351567   213.841241